# Generated by Django 6.0.3 on 2026-03-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('image', models.ImageField(null=True, upload_to='artists/')),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(help_text='Длительность в секундах'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.artist'),
        ),
    ]
